# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 01:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0004_auto_20160912_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(default='content', max_length=1024),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 1, 41, 22, 25386, tzinfo=utc), verbose_name='date published'),
        ),
    ]
