# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0009_auto_20160914_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 6, 6, 9, 219520, tzinfo=utc), verbose_name='date published'),
        ),
    ]
