# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0010_auto_20160914_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 6, 15, 23, 144868, tzinfo=utc), verbose_name='date published'),
        ),
    ]
