# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0011_auto_20160914_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 14, 3, 34, 708399, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
