# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0015_auto_20160917_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Show',
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 6, 3, 22, 404487, tzinfo=utc), verbose_name='date published'),
        ),
    ]
