# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0018_auto_20160917_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 7, 42, 45, 390407, tzinfo=utc), verbose_name='date published'),
        ),
    ]
