# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0019_auto_20160918_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 25, 21, 0, 0, 613501, tzinfo=utc), verbose_name='date published'),
        ),
    ]
