# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0020_auto_20160925_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url',
            field=models.URLField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 27, 5, 3, 26, 40994, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.IntegerField(),
        ),
    ]
