# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0021_auto_20160926_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 27, 5, 31, 53, 530552, tzinfo=utc), verbose_name='date published'),
        ),
    ]
